@startuml database
object Tag{
    id **PK**
    title
}

object NonProfit{
    id **PK**
    name
    description
}

object NPToTag{
    tag_id **PK, FK**
    np_id **PK, FK**
}

Tag -- NonProfit
(Tag, NonProfit) .. NPToTag

@enduml